### ISSUE TITLE
SAPCC 2.13.0: Unable to access jarfile

### ISSUE THREAD

**Issue by gnnivlek** [nzamani/sap-cloud-connector-docker#31] opened 2021-01-21 09:57 UTC
Hi, I have followed the instruction and change the version of the cloud connector to the current version (SAPCC 2.13.0), but after successfully running the Dockerfile, the generated image seems to have a problem when accessing the jarfile plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar.  Is there any solution for this issue?
I noticed that the props.ini on the current version does not have this -jar command and I can't compare it with previous version since there's no way to download it now. Thank you.

**Comment by skandasoft** [comment] 2021-01-21 22:32
had the same exact same issue...and tried removing it and still it failed

**Comment by cicerojs** [comment] 2021-01-23 18:08
Hi, I had the following issue when I change the sapcc version to latest version in Dockfile: 
error: open of com.sap.scc-ui-2.13.0.x86_64-4.rpm failed: No such file or directory

**Comment by nzamani** [comment] 2021-01-24 18:46
All fixed via cab892f465949a88c52212090c4e7835fe9f643c

**Comment by skandasoft** [comment] 2021-02-01 01:39
Error: Unable to access jarfile plugins/org.eclipse.equinox.launcher_1.1.0.v20100507.jar

**Comment by nzamani** [comment] 2021-02-01 17:38
@skandasoft are you using the latest version of my dockerfile + building it etc? So far I couldn't reproduce the issue on my own...

**Comment by skandasoft** [comment] 2021-02-04 21:33
Thanks for putting this out.

I tried pulling the latest version. And I saw the latest docker file getting pulled. And when I build on it (even with --no-cache) it was giving the same error. 
Now I re-cloned into another directory and tried it is working. 👍 

I now have to figure the difference between the cloud foundry/neo user. the cloud foundry doesn't have the cloud connector link in there but I was able to connect to that subdomain/user successfully. 

Now I am trying to connect to local ABAP but it doesn't seem to do a check against it. Should I raise a ticket here or in your youtube. it is in the same network. I guess I have to put the 502 certificate in there.

**Comment by nzamani** [comment] 2021-02-06 19:46
I consider this to be done/confirmed now.

Just some hints (I had to read you message again and again many many times to understand what you mean, I hope I got it right):

1. In the **SAPCF Cockpit** you can't currently see the connected SAPCCs. This feature is not yet available in the SAPCF Cockpit in case you have a **Feature Set B Global Account**. I can't change this, we all have to wait I guess. That's not an issue as long as inside the SAPCC UI you can confirm that the connection worked - and it seems to work in your case.
2. In the **SAPCF Cockpit** the "Check" button for destinations going to an onPrem ABAP is currently always showing a connection error when you press the button. However, this is currently a false alert because again this feature is not yet available in the SAPCF Cockpit in case you have a **Feature Set B Global Account**. The best way to test a working connectivity is by calling an OData service via its SAPCP url. No idea what exactly you mean with 502 certificate.
3. I don't check YouTube for issues. GitHub should get the tickets. However, in your case I have the feeling you have a local issue.

**Closed by nzamani** 2021-02-06 19:46 UTC

**Comment by skandasoft** [comment] 2021-02-07 02:39
Yes. Confirmed as done. You can close. 

Thanks for taking time to answer my question.

1. As you mentioned, I cannot see the connected sapcc's. And on top of it check button in destinations would not say successful.
2. And of course sap don't support webide any  more.
3. But I was able to connect to BAS. Guess what, I cannot deploy to my local SAP because it nw752 and BAS need S/4 hana
